# Generated by Django 6.0.4 on 2026-04-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Godet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinceF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vrac_type', models.CharField(blank=True, max_length=50)),
                ('pompe', models.CharField(blank=True, max_length=50)),
                ('etuve', models.CharField(blank=True, max_length=50)),
                ('temperature', models.CharField(blank=True, max_length=50)),
                ('Nom_vrac', models.CharField(blank=True, max_length=50)),
                ('circuit_ferme_microbio', models.CharField(blank=True, max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('labo_validation', models.CharField(blank=True, max_length=50)),
                ('microbio_validation', models.CharField(blank=True, max_length=50)),
                ('marque', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReglageEKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('ref', models.CharField(max_length=200)),
                ('nom_produit', models.CharField(blank=True, max_length=200)),
                ('numeros_of', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('numeros_lot', models.CharField(db_index=True, max_length=100)),
                ('date_reglage', models.DateField(blank=True, null=True)),
                ('regleur', models.CharField(blank=True, max_length=50)),
                ('observation', models.CharField(blank=True, max_length=1000, null=True)),
                ('moussant', models.CharField(blank=True, max_length=10)),
                ('ref_flacon', models.CharField(blank=True, max_length=100)),
                ('programme', models.CharField(blank=True, max_length=50)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('volume_demarrage', models.FloatField(blank=True, null=True)),
                ('filtre', models.CharField(blank=True, max_length=10)),
                ('pompe_1', models.CharField(blank=True, max_length=10, null=True)),
                ('motorise_1', models.CharField(blank=True, max_length=10)),
                ('valeur_1', models.FloatField(blank=True, null=True)),
                ('bute_bec_1', models.CharField(blank=True, max_length=50, null=True)),
                ('pompe_2', models.CharField(blank=True, max_length=10, null=True)),
                ('motorise_2', models.CharField(blank=True, max_length=10)),
                ('valeur_2', models.FloatField(blank=True, null=True)),
                ('bute_bec_2', models.CharField(blank=True, max_length=50, null=True)),
                ('pompe_3', models.CharField(blank=True, max_length=50, null=True)),
                ('motorise_3', models.CharField(blank=True, max_length=10)),
                ('valeur_3', models.FloatField(blank=True, null=True)),
                ('bute_bec_3', models.CharField(blank=True, max_length=50, null=True)),
                ('pompe_4', models.CharField(blank=True, max_length=10, null=True)),
                ('valeur_4', models.FloatField(blank=True, null=True)),
                ('bute_bec_4', models.CharField(blank=True, max_length=50, null=True)),
                ('type_bec', models.CharField(blank=True, max_length=50)),
                ('h_machine', models.FloatField(blank=True, null=True)),
                ('ctrl_jus_h', models.CharField(blank=True, max_length=10)),
                ('ctrl_jus_prof', models.CharField(blank=True, max_length=10)),
                ('ctrl_ultra', models.CharField(blank=True, max_length=10)),
                ('h_compo_1', models.FloatField(blank=True, null=True)),
                ('presence_marteau', models.CharField(blank=True, max_length=10)),
                ('h_marteau', models.FloatField(blank=True, null=True)),
                ('embout', models.CharField(blank=True, max_length=50)),
                ('h_compo_2', models.FloatField(blank=True, null=True)),
                ('presence_visseuse', models.CharField(blank=True, max_length=10)),
                ('couple_vis', models.FloatField(blank=True, null=True)),
                ('h_pince_ext', models.FloatField(blank=True, null=True)),
                ('h_pince_int', models.FloatField(blank=True, null=True)),
                ('cadence', models.FloatField(blank=True, null=True)),
                ('visseuse', models.CharField(blank=True, max_length=50)),
                ('h_finale', models.FloatField(blank=True, null=True)),
                ('convoyeur', models.CharField(blank=True, max_length=50)),
                ('cames_bec_on', models.CharField(blank=True, max_length=50)),
                ('cames_bec_off', models.CharField(blank=True, max_length=50)),
                ('presence_cueilleur', models.CharField(blank=True, max_length=10)),
                ('cueilleur', models.CharField(blank=True, max_length=50)),
                ('cueilleur_1', models.CharField(blank=True, max_length=50)),
                ('cueilleur_2', models.CharField(blank=True, max_length=50)),
                ('cueilleur_3', models.CharField(blank=True, max_length=50)),
                ('hauteur_rail', models.FloatField(blank=True, null=True)),
                ('etiquette', models.CharField(blank=True, max_length=50)),
                ('consigne_etiquette', models.TextField(blank=True)),
                ('etiqueteuse', models.CharField(blank=True, max_length=50)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butee_vis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.bute')),
                ('centerur_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1', to='machines.centreur')),
                ('centerur_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2', to='machines.centreur')),
                ('centerur_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3', to='machines.centreur')),
                ('centerur_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p4', to='machines.centreur')),
                ('godet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.godet')),
                ('of_lavage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglages_lavage_suivants', to='machines.reglageeko')),
                ('of_precedent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglages_suivants', to='machines.reglageeko')),
                ('pince_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.pincef')),
                ('pince_vis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.pince')),
                ('tube_bec_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tubes_bec_p1', to='machines.bec')),
                ('tube_bec_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tubes_bec_p2', to='machines.bec')),
                ('tube_bec_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tubes_bec_p3', to='machines.bec')),
                ('tube_bec_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tubes_bec_p4', to='machines.bec')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vrac_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglages', to='machines.vrac')),
            ],
            options={
                'ordering': ['-date_reglage'],
            },
        ),
        migrations.CreateModel(
            name='ReglageEKOHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reglage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='machines.reglageeko')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
