# Generated by Django 6.0.4 on 2026-04-23 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglageEKOChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_from', models.PositiveIntegerField()),
                ('version_to', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reglage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='machines.reglageeko')),
            ],
            options={
                'ordering': ['version_to', 'changed_at'],
            },
        ),
    ]
