# Generated by Django 6.0.4 on 2026-04-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglageeko',
            name='of_lavage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglages_lavage_suivants', to='machines.reglageeko'),
        ),
        migrations.AlterField(
            model_name='reglageeko',
            name='of_precedent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglages_suivants', to='machines.reglageeko'),
        ),
    ]
