# Generated by Django 6.0.4 on 2026-04-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_godet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglageeko',
            name='godet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.godet'),
        ),
    ]
