# Generated by Django 6.0.4 on 2026-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_reglageekochange'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglageeko',
            name='machine',
            field=models.CharField(choices=[('EKO', 'EKO'), ('G1', 'G1'), ('K', 'K'), ('N', 'N'), ('A', 'A'), ('Dumek', 'Dumek')], default='EKO', max_length=10),
        ),
    ]
