# Generated by Django 6.0.4 on 2026-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_reglageeko_godet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglageeko',
            name='numeros_of',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
