# Generated by Django 6.0.4 on 2026-04-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_remove_reglageeko_vrac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglageeko',
            name='vrac',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_Nom_vrac',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_circuit_ferme_microbio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_etuve',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_labo_validation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_microbio_validation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_pompe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglages', to='machines.vrac'),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_temperature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
