# Generated by Django 6.0.4 on 2026-04-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_reglageeko_vrac_reglageeko_vrac_nom_vrac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_Nom_vrac',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_circuit_ferme_microbio',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_commentaire',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_etuve',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_labo_validation',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_microbio_validation',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_pompe',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_temperature',
        ),
        migrations.RemoveField(
            model_name='reglageeko',
            name='vrac_type',
        ),
    ]
