# Generated by Django 6.0.4 on 2026-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_remove_reglageeko_vrac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglageeko',
            name='vrac',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_Nom_vrac',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_circuit_ferme_microbio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_etuve',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_labo_validation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_microbio_validation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_pompe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_temperature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reglageeko',
            name='vrac_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
