# Generated by Django 6.0.4 on 2026-04-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_reglageeko_vrac_reglageeko_vrac_nom_vrac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglageeko',
            name='vrac_circuit_ferme_microbio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reglageeko',
            name='vrac_labo_validation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reglageeko',
            name='vrac_microbio_validation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
