# Generated by Django 6.0.4 on 2026-04-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_alter_reglageeko_numeros_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglageeko',
            name='observation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
