# Generated by Django 6.0.4 on 2026-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_alter_reglageeko_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglageeko',
            name='date_reglage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
