# Generated by Django 6.0.4 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_remove_reglageeko_vrac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrac',
            name='marque',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
