# Generated by Django 6.0.4 on 2026-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_vrac_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglageeko',
            name='numeros_of',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
